### ISSUE TITLE
Regarding the conversion of files to data urls, a less than condition was found to be missing

### ISSUE THREAD

**Issue by sbigtree** [webpack-contrib/url-loader#186] opened 2019-07-11 03:42 UTC
![image](https://user-images.githubusercontent.com/48344438/61020493-90d64f80-a3d0-11e9-919c-da3112ad3b1d.png)
`module: {
          rules: [
            {
              test: /\.(png|jpg|gif)$/,
              use: [
                {
                  loader: 'url-loader',
                  options: {
                    limit: 8192
                  }
                }
              ]
            }
          ]
        }`

I found this code in the official website document, which was just to convert files larger than 8k into base64, while I wanted to convert pictures smaller than 8k into base64, but I could not find this configuration API in the official website document

**Comment by evilebottnawi** [comment] 2019-07-11 11:10
It looks like you just deleted our lovely crafted issue template. It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please either update the issue with the template and reopen, or open a new issue.

Sorry i can't reproduce

**Closed by evilebottnawi** 2019-07-11 11:10 UTC
